name: Delivery

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: udpate apt
        run: sudo apt-get update
      - name: install dependencies
        run: npm ci --no-progress
      - name: test package
        run: npm run test
      - name: publish package
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
